export const DISCIPLESHIP = {
  'Sigue al Señor':[
    { book: 'Deuteronomio 5', passage: '33 Andad en todo el camino que Jehová vuestro Dios os ha mandado, para que viváis y os vaya bien, y tengáis largos días en la tierra que habéis de poseer.'},
    { book: 'Deuteronomio 31', passage: '8 Y Jehová va delante de ti; él estará contigo, no te dejará, ni te desamparará; no temas ni te intimides.'},
    { book: 'Salmo 119', passage: '133 Ordena mis pasos con tu palabra, Y ninguna iniquidad se enseñoree de mí.'},
    { book: 'Juan 8', passage: '12 Otra vez Jesús les habló, diciendo: Yo soy la luz del mundo; el que me sigue, no andará en tinieblas, sino que tendrá la luz de la vida.'},
    { book: '2 Tesalonicenses 3', passage: '5 El Señor encamine vuestros corazones al amor de Dios, y a la paciencia de Cristo.'},
    { book: 'Deuteronomio 13', passage: '4 En pos de Jehová vuestro Dios andaréis; a él temeréis, guardaréis sus mandamientos y escucharéis su voz, a él serviréis, y a él seguiréis.'},
    { book: 'Mateo 10', passage: '38 Y el que no toma su cruz y sigue en pos de mí, no es digno de mí.'},
    { book: 'Marcos 8', passage: '34 Y llamando a la gente y a sus discípulos, les dijo: Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.'},
    { book: 'Gálatas 5', passage: '25 Si vivimos por el Espíritu, andemos también por el Espíritu."'},
    { book: 'Efesios 5', passage: '1 Sed, pues, imitadores de Dios como hijos amados.'},
    { book: 'Juan 12', passage: '26 Si alguno me sirve, sígame; y donde yo estuviere, allí también estará mi servidor. Si alguno me sirviere, mi Padre le honrará'},
    { book: 'Salmo 128', passage: '1 Bienaventurado todo aquel que teme a Jehová, Que anda en sus caminos.'},
    { book: '1 Pedro 2', passage: '21 Pues para esto fuisteis llamados; porque también Cristo padeció por nosotros, dejándonos ejemplo, para que sigáis sus pisadas.'},
    { book: 'Salmo 37', passage: '23 Por Jehová son ordenados los pasos del hombre, Y él aprueba su camino.'},
    { book: 'Efesios 2', passage: '10 Porque somos hechura suya, creados en Cristo Jesús para buenas obras, las cuales Dios preparó de antemano para que anduviésemos en ellas.'},
  ],
  'Esperanza':[
    { book: 'Jeremías 29', passage: '11 Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.'},
    { book: 'Salmo 42', passage: '11 ¿Por qué te abates, oh alma mía, Y por qué te turbas dentro de mí? Espera en Dios; porque aún he de alabarle, Salvación mía y Dios mío.'},
    { book: 'Isaías 40', passage: '3 Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.'},
    { book: 'Salmo 121', passage: '7-8 Jehová te guardará de todo mal; El guardará tu alma. Jehová guardará tu salida y tu entrada Desde ahora y para siempre.'},
    { book: 'Romanos 15', passage: '13 Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por el poder del Espíritu Santo.'},
    { book: 'Mateo 11', passage: '28 Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.'},
    { book: 'Hebreos 11', passage: '1 Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.'},
    { book: '1 Corintios 13', passage: '13 Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.'},
    { book: 'Romanos 5', passage: '3-4 Y no sólo esto, sino que también nos gloriamos en las tribulaciones, sabiendo que la tribulación produce paciencia; y la paciencia, prueba; y la prueba, esperanza.'},
    { book: 'Salmo 119', passage: '114 Mi escondedero y mi escudo eres tú; En tu palabra he esperado.'},
    { book: 'Hebreos 10', passage: '23 Mantengamos firme, sin fluctuar, la profesión de nuestra esperanza, porque fiel es el que prometió.'},
    { book: 'Salmo 31', passage: '24 Esforzaos todos vosotros los que esperáis en Jehová, Y tome aliento vuestro corazón.'},
    { book: 'Romanos 8', passage: '25 Pero si esperamos lo que no vemos, con paciencia lo aguardamos.'},
    { book: 'Miqueas 7', passage: '7 Mas yo a Jehová miraré, esperaré al Dios de mi salvación; el Dios mío me oirá.'},
    { book: 'Proverbios 13', passage: '12 La esperanza que se demora es tormento del corazón; Pero árbol de vida es el deseo cumplido.'},
  ],
  'Amor': [
    { book: '1 Corintios 13', passage: '4-5 El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece; no hace nada indebido, no busca lo suyo, no se irrita, no guarda rencor.'},
    { book: '1 Corintios 16', passage: '14 Todas vuestras cosas sean hechas con amor.'},
    { book: 'Salmo 143', passage: '8 Hazme oír por la mañana tu misericordia, Porque en ti he confiado; Hazme saber el camino por donde ande, Porque a ti he elevado mi alma.'},
    { book: 'Colosenses 3', passage: '14 Y sobre todas estas cosas vestíos de amor, que es el vínculo perfecto.'},
    { book: 'Proverbios 3', passage: '3-4 Nunca se aparten de ti la misericordia y la verdad; Atalas a tu cuello, Escríbelas en la tabla de tu corazón; Y hallarás gracia y buena opinión Ante los ojos de Dios y de los hombres.'},
    { book: '1 Juan 4', passage: '16 Y nosotros hemos conocido y creído el amor que Dios tiene para con nosotros. Dios es amor; y el que permanece en amor, permanece en Dios, y Dios en él.'},
    { book: 'Efesios 4', passage: '2 Con toda humildad y mansedumbre, soportándoos con paciencia los unos a los otros en amor.'},
    { book: '1 Juan 4', passage: '19 Nosotros le amamos a él, porque él nos amó primero.'},
    { book: '1 Corintios 13', passage: '13 Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.'},
    { book: '1 Pedro 4', passage: '8 Y ante todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados.'},
    { book: 'Romanos 12', passage: '9 El amor sea sin fingimiento. Aborreced lo malo, seguid lo bueno."'},
    { book: 'Efesios 3', passage: '16-17 Para que os dé, conforme a las riquezas de su gloria, el ser fortalecidos con poder en el hombre interior por su Espíritu; para que habite Cristo por la fe en vuestros corazones, a fin de que, arraigados y cimentados en amor.'},
    { book: '1 Corintios 13', passage: '2 Y si tuviese profecía, y entendiese todos los misterios y toda ciencia, y si tuviese toda la fe, de tal manera que trasladase los montes, y no tengo amor, nada soy.'},
    { book: 'Juan 15', passage: '12 Este es mi mandamiento: Que os améis unos a otros, como yo os he amado.'},
  ],
  'Perdón': [
    { book: 'Proverbios 17', passage: '9 El que cubre la falta busca amistad; Mas el que la divulga, aparta al amigo.'},
    { book: 'Efesios 4', passage: '32 Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros, como Dios también os perdonó a vosotros en Cristo.'},
    { book: 'Mateo 6', passage: '14 Porque si perdonáis a los hombres sus ofensas, os perdonará también a vosotros vuestro Padre celestial.'},
    { book: 'Colosenses 3', passage: '13 Soportándoos unos a otros, y perdonándoos unos a otros si alguno tuviere queja contra otro. De la manera que Cristo os perdonó, así también hacedlo vosotros.'},
    { book: '2 Crónicas 7', passage: '14 Si se humillare mi pueblo, sobre el cual mi nombre es invocado, y oraren, y buscaren mi rostro, y se convirtieren de sus malos caminos; entonces yo oiré desde los cielos, y perdonaré sus pecados, y sanaré su tierra.'},
    { book: 'Lucas 6', passage: '37 No juzguéis, y no seréis juzgados; no condenéis, y no seréis condenados; perdonad, y seréis perdonados.'},
    { book: 'Mateo 18', passage: '21-22 Entonces se le acercó Pedro y le dijo: Señor, ¿cuántas veces perdonaré a mi hermano que peque contra mí? ¿Hasta siete? Jesús le dijo: No te digo hasta siete, sino aun hasta setenta veces siete."'},
    { book: 'Proverbios 28', passage: '13 El que encubre sus pecados no prosperará; Mas el que los confiesa y se aparta alcanzará misericordia.",'},
    { book: 'Salmo 86', passage: '5 Porque tú, Señor, eres bueno y perdonador, Y grande en misericordia para con todos los que te invocan.'},
    { book: 'Miqueas 7', passage: '18 ¿Qué Dios como tú, que perdona la maldad, y olvida el pecado del remanente de su heredad? No retuvo para siempre su enojo, porque se deleita en misericordia.'},
    { book: 'Marcos 11', passage: '25 Y cuando estéis orando, perdonad, si tenéis algo contra alguno, para que también vuestro Padre que está en los cielos os perdone a vosotros vuestras ofensas.'},
    { book: 'Hechos 13', passage: '38-39 Sabed, pues, esto, varones hermanos: que por medio de él se os anuncia perdón de pecados, y que de todo aquello de que por la ley de Moisés no pudisteis ser justificados, en él es justificado todo aquel que cree.'},
    { book: '1 Juan 2', passage: '2 Y él es la propiciación por nuestros pecados; y no solamente por los nuestros, sino también por los de todo el mundo.'},
    { book: 'Salmo 32', passage: '5 Mi pecado te declaré, y no encubrí mi iniquidad. Dije: Confesaré mis transgresiones a Jehová; Y tú perdonaste la maldad de mi pecado. Selah'},
    { book: 'Joel 2', passage: '13 Rasgad vuestro corazón, y no vuestros vestidos, y convertíos a Jehová vuestro Dios; porque misericordioso es y clemente, tardo para la ira y grande en misericordia, y que se duele del castigo.'},
  ],
  'Familia': [
    { book: 'Deuteronomio 6', passage: '6-7 Y estas palabras que yo te mando hoy, estarán sobre tu corazón; y las repetirás a tus hijos, y hablarás de ellas estando en tu casa, y andando por el camino, y al acostarte, y cuando te levantes.'},
    { book: 'Hechos 16', passage: '31 Ellos dijeron: Cree en el Señor Jesucristo, y serás salvo, tú y tu casa.'},
    { book: '1 Corintios 1', passage: '10 Os ruego, pues, hermanos, por el nombre de nuestro Señor Jesucristo, que habléis todos una misma cosa, y que no haya entre vosotros divisiones, sino que estéis perfectamente unidos en una misma mente y en un mismo parecer.'},
    { book: 'Proverbios 6', passage: '20 Guarda, hijo mío, el mandamiento de tu padre, Y no dejes la enseñanza de tu madre.'},
    { book: '1 Juan 4', passage: '20 Si alguno dice: Yo amo a Dios, y aborrece a su hermano, es mentiroso. Pues el que no ama a su hermano a quien ha visto, ¿cómo puede amar a Dios a quien no ha visto?'},
    { book: 'Salmo 133', passage: '1 ¡Mirad cuán bueno y cuán delicioso es Habitar los hermanos juntos en armonía!"'},
    { book: 'Isaías 49', passage: '15-16 ¿Se olvidará la mujer de lo que dio a luz, para dejar de compadecerse del hijo de su vientre? Aunque olvide ella, yo nunca me olvidaré de ti. He aquí que en las palmas de las manos te tengo esculpida; delante de mí están siempre tus muros.'},
    { book: 'Salmo 103', passage: '17-18 Mas la misericordia de Jehová es desde la eternidad y hasta la eternidad sobre los que le temen, Y su justicia sobre los hijos de los hijos; Sobre los que guardan su pacto, Y los que se acuerdan de sus mandamientos para ponerlos por obra.'},
    { book: 'Efesios 6', passage: '4 Y vosotros, padres, no provoquéis a ira a vuestros hijos, sino criadlos en disciplina y amonestación del Señor.'},
    { book: 'Proverbios 22', passage: '6 Instruye al niño en su camino, Y aun cuando fuere viejo no se apartará de él.'},
    { book: 'Éxodo 20', passage: '12 Honra a tu padre y a tu madre, para que tus días se alarguen en la tierra que Jehová tu Dios te da.'},
    { book: '1 Timoteo 5', passage: '8 orque si alguno no provee para los suyos, y mayormente para los de su casa, ha negado la fe, y es peor que un incrédulo.'},
    { book: 'Proverbios 17', passage: '17 En todo tiempo ama el amigo, Y es como un hermano en tiempo de angustia.'},
    { book: 'Proverbios 17', passage: '6 Corona de los viejos son los nietos, Y la honra de los hijos, sus padres.'},
    { book: '1 Reyes 8', passage: '57 Esté con nosotros Jehová nuestro Dios, como estuvo con nuestros padres, y no nos desampare ni nos deje.'},
  ],
  'Matrimonio':[
    { book: 'Proverbios 18', passage: '22 El que halla esposa halla el bien, Y alcanza la benevolencia de Jehová.'},
    { book: 'Mateo 19', passage: '4-6 Él, respondiendo, les dijo: ¿No habéis leído que el que los hizo al principio, varón y hembra los hizo, y dijo: Por esto el hombre dejará padre y madre, y se unirá a su mujer, y los dos serán una sola carne? Así que no son ya más dos, sino una sola carne; por tanto, lo que Dios juntó, no lo separe el hombre.'},
    { book: 'Colosenses 3', passage: '18-19 Casadas, estad sujetas a vuestros maridos, como conviene en el Señor. Maridos, amad a vuestras mujeres, y no seáis ásperos con ellas.'},
    { book: 'Hebreos 13', passage: '4 Honroso sea en todos el matrimonio, y el lecho sin mancilla; pero a los fornicarios y a los adúlteros los juzgará Dios.'},
    { book: 'Proverbios 31', passage: '10 Mujer virtuosa, ¿quién la hallará? Porque su estima sobrepasa largamente a la de las piedras preciosas.'},
    { book: 'Efesios 5', passage: '25-26 Maridos, amad a vuestras mujeres, así como Cristo amó a la iglesia, y se entregó a sí mismo por ella, para santificarla, habiéndola purificado en el lavamiento del agua por la palabra.'},
    { book: 'Proverbios 16', passage: '9 El corazón del hombre piensa su camino; Mas Jehová endereza sus pasos'},
    { book: '1 Corintios 7', passage: '2 Pero a causa de las fornicaciones, cada uno tenga su propia mujer, y cada una tenga su propio marido.'},
    { book: 'Génesis 2', passage: '18 Y dijo Jehová Dios: No es bueno que el hombre esté solo; le haré ayuda idónea para él.'},
    { book: 'Deuteronomio 24', passage: '5 Cuando alguno fuere recién casado, no saldrá a la guerra, ni en ninguna cosa se le ocupará; libre estará en su casa por un año, para alegrar a la mujer que tomó.'},
    { book: 'Génesis 2', passage: '22-24 Y de la costilla que Jehová Dios tomó del hombre, hizo una mujer, y la trajo al hombre. Dijo entonces Adán: Esto es ahora hueso de mis huesos y carne de mi carne; ésta será llamada Varona, porque del varón fue tomada. Por tanto, dejará el hombre a su padre y a su madre, y se unirá a su mujer, y serán una sola carne.'},
    { book: 'Efesios 5', passage: '22-23 Las casadas estén sujetas a sus propios maridos, como al Señor; porque el marido es cabeza de la mujer, así como Cristo es cabeza de la iglesia, la cual es su cuerpo, y él es su Salvador.'},
  ],
  'Salvación':[
    { book: 'Hechos 4', passage: '12 Y en ningún otro hay salvación; porque no hay otro nombre bajo el cielo, dado a los hombres, en que podamos ser salvos.'},
    { book: 'Hechos 16', passage: '31 Ellos dijeron: Cree en el Señor Jesucristo, y serás salvo, tú y tu casa.'},
    { book: '2 Timoteo 1', passage: '9 Quien nos salvó y llamó con llamamiento santo, no conforme a nuestras obras, sino según el propósito suyo y la gracia que nos fue dada en Cristo Jesús antes de los tiempos de los siglos.'},
    { book: 'Salmo 62', passage: '1 En Dios solamente está acallada mi alma; De él viene mi salvación.'},
    { book: 'Hechos 2', passage: '21 Y todo aquel que invocare el nombre del Señor, será salvo.'},
    { book: '1 Corintios 6', passage: '9-10 ¿No sabéis que los injustos no heredarán el reino de Dios? No erréis; ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados, ni los que se echan con varones, ni los ladrones, ni los avaros, ni los borrachos, ni los maldicientes, ni los estafadores, heredarán el reino de Dios.'},
    { book: 'Romanos 10', passage: '10 Porque con el corazón se cree para justicia, pero con la boca se confiesa para salvación.'},
    { book: 'Tito 2', passage: '11-12 Porque la gracia de Dios se ha manifestado para salvación a todos los hombres, enseñándonos que, renunciando a la impiedad y a los deseos mundanos, vivamos en este siglo sobria, justa y piadosamente.'},
    { book: 'Lucas 19', passage: '10 Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.'},
    { book: '2 Pedro 3', passage: '9 El Señor no retarda su promesa, según algunos la tienen por tardanza, sino que es paciente para con nosotros, no queriendo que ninguno perezca, sino que todos procedan al arrepentimiento.'},
    { book: 'Lucas 18', passage: '27 Él les dijo: Lo que es imposible para los hombres, es posible para Dios.'},
    { book: 'Marcos 16', passage: '16 El que creyere y fuere bautizado, será salvo; mas el que no creyere, será condenado.'},
    { book: 'Mateo 7', passage: '13-14 Entrad por la puerta estrecha; porque ancha es la puerta, y espacioso el camino que lleva a la perdición, y muchos son los que entran por ella; porque estrecha es la puerta, y angosto el camino que lleva a la vida, y pocos son los que la hallan.'},
    { book: '1 Pedro 1', passage: '8-9 A quien amáis sin haberle visto, en quien creyendo, aunque ahora no lo veáis, os alegráis con gozo inefable y glorioso; obteniendo el fin de vuestra fe, que es la salvación de vuestras almas.'},
    { book: 'Hebreos 9', passage: '28 Así también Cristo fue ofrecido una sola vez para llevar los pecados de muchos; y aparecerá por segunda vez, sin relación con el pecado, para salvar a los que le esperan.'},
  ],
  'Finanzas':[
    { book: 'Hebreos 13', passage: '5 Sean vuestras costumbres sin avaricia, contentos con lo que tenéis ahora; porque él dijo: No te desampararé, ni te dejaré.'},
    { book: 'Proverbios 13', passage: '11 Las riquezas de vanidad disminuirán; Pero el que recoge con mano laboriosa las aumenta.'},
    { book: '1 Timoteo 6', passage: '9 Porque los que quieren enriquecerse caen en tentación y lazo, y en muchas codicias necias y dañosas, que hunden a los hombres en destrucción y perdición.'},
    { book: 'Proverbios 23', passage: '4 No te afanes por hacerte rico; Sé prudente, y desiste.'},
    { book: 'Proverbios 10', passage: '22 La bendición de Jehová es la que enriquece, Y no añade tristeza con ella.'},
    { book: 'Eclesiastés 5', passage: '10 El que ama el dinero, no se saciará de dinero; y el que ama el mucho tener, no sacará fruto. También esto es vanidad.'},
    { book: 'Proverbios 3', passage: '9 Honra a Jehová con tus bienes, Y con las primicias de todos tus frutos.'},
    { book: 'Proverbios 15', passage: '16 Mejor es lo poco con el temor de Jehová, Que el gran tesoro donde hay turbación.'},
    { book: 'Lucas 12', passage: '15 Y les dijo: Mirad, y guardaos de toda avaricia; porque la vida del hombre no consiste en la abundancia de los bienes que posee.'},
    { book: 'Mateo 6', passage: '21 Porque donde esté vuestro tesoro, allí estará también vuestro corazón.'},
    { book: 'Romanos 13', passage: '7 Pagad a todos lo que debéis: al que tributo, tributo; al que impuesto, impuesto; al que respeto, respeto; al que honra, honra.'},
    { book: 'Proverbios 16', passage: '16 Mejor es adquirir sabiduría que oro preciado; Y adquirir inteligencia vale más que la plata.'},
    { book: '1 Crónicas 29', passage: '14 Porque ¿quién soy yo, y quién es mi pueblo, para que pudiésemos ofrecer voluntariamente cosas semejantes? Pues todo es tuyo, y de lo recibido de tu mano te damos.'},
    { book: '1 Timoteo 6', passage: '17 A los ricos de este siglo manda que no sean altivos, ni pongan la esperanza en las riquezas, las cuales son inciertas, sino en el Dios vivo, que nos da todas las cosas en abundancia para que las disfrutemos.'},
    { book: 'Mateo 25', passage: '21 Vanidad y palabra mentirosa aparta de mí; No me des pobreza ni riquezas; Manténme del pan necesario.'},
  ]
};
